dbc:
    replay_buffer_capacity: 1_000_000
    num_train_steps: 1_000_000
    hidden_dim: 256
    encoder_feature_dim: 50
    batch_size: 512
    lr: 0.00001
dbc_robust:
    replay_buffer_capacity: 50_000
    num_train_steps: null
    encoder_feature_dim: null
    hidden_dim: null
    batch_size: null
    lr: null
mico:
    replay_buffer_capacity: 1_000_000
    num_train_steps: 400_000
    encoder_feature_dim: null
    hidden_dim: null
    batch_size: null
    lr: null
rap:
    replay_buffer_capacity: 1_000_000
    num_train_steps: 1_000_000
    encoder_feature_dim: 100
    hidden_dim: 1024
    batch_size: 128
    lr: 0.0005
ours:
    replay_buffer_capacity: 1_000_000
    num_train_steps: 1_000_000
    encoder_feature_dim: 50
    hidden_dim: 256
    batch_size: 128
    lr: 0.00001