name: DBC
exp_mode: ???
overrides:
  model:
    encoder_mode: dbc
    critic_lr: 0.00001
    actor_lr: 0.00001
    encoder_lr: 0.00001
    residual_actor: True
sweeper:
  name: dbc_2
  num_runs: 8
  parameters:
    model:
      critic_lr: {values: [0.00001, 0.000001]}
      actor_lr: {values: [0.00001, 0.000001]}
      encoder_lr: {values: [0.00001, 0.000001]}