version: "2"
services:
  bisim:
    # build: .
    image: ghcr.io/sandeshadhikary/bisim:latest
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
    environment:
      - MUJOCO_GL=egl
    volumes: 
      - configdata:/optuna_storage
      - $PWD/src:/src
volumes:
  configdata:
    driver: rclone
    driver_opts:
      remote: 'GDrive:bisim'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0