version: "3"
services:
  bisim:
    image: ghcr.io/sandeshadhikary/bisim:latest
    container_name: sandesh_bisim
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
    environment:
      - MUJOCO_GL=egl
    volumes: 
      - ./src:/project/src
      - ./scripts:/project/scripts
      - ./workdir:/project/workdir
      - ./logdir:/project/logdir