version: "3"
services:
  bisim:
    image: ghcr.io/sandeshadhikary/bisim:latest
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
    environment:
      - MUJOCO_GL=egl
    volumes: 
      - $PWD/src:/project/src
      - $PWD/workdir:/project/workdir
      - $PWD/logdir:/project/logdir