version: "2"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: 
                - gpu
                - utility
                - compute
                - video
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTH
      - SDL_VIDEODRIVER=X11
      - MUJOCO_GL=egl
    volumes:
      - $XSOCK:$XSOCK
      - $XAUTH:$XAUTH
      - $PWD/src:/src
    network_mode: host
    ports:
      - 6006:6006 # tensorboard
