name: cartpole_500k
desc: |
  Carttpole swingup but with 500k replay buffer.
overrides:
  trainer:
    env:
      domain_name: cartpole
      task_name: swingup
      img_source: null
      action_repeat: 8
    eval_env:
      action_repeat: 8
    replay_buffer:
      replay_buffer_capacity: 500_000