name: cartpole_kinetics
desc: |
  Carttpole swingup with kinetics video distractors
overrides:
  trainer:
    env:
      domain_name: cartpole
      task_name: swingup
      img_source: kinetics_videos