name: cheetah_baseline
desc: |
  Cheetah Run
overrides:
  trainer:
    env:
      domain_name: cheetah
      task_name: run
      img_source: null
      action_repeat: 4
    eval_env:
      action_repeat: 4