name: test
desc: |
  Test Project
overrides:
  model:
    trunk_regularization: false
    encoder_feature_dim: 50
  trainer:
    eval_freq: 99
    log_epoch_freq: 10
    init_steps: 10
    num_train_steps: 1000
    save_checkpoint_freq: 100
    terminal_display: rich
    replay_buffer:
      replay_buffer_capacity: 5000
    env:
      domain_name: finger
      task_name: spin
      img_source: null
      action_repeat: 4
    eval_env:
      action_repeat: 4
