name: walker_stand_kinetics_baseline
desc: |
  Walker stand
overrides:
  trainer:
    env:
      domain_name: walker
      task_name: stand
      img_source: kinetics_videos
      action_repeat: 2
    eval_env:
      action_repeat: 2