name: walker_baseline
desc: |
  Walker walk
overrides:
  trainer:
    env:
      domain_name: walker
      task_name: walk
      img_source: null
      action_repeat: 2
    eval_env:
      action_repeat: 2