exp_mode: train
trainer:
  hidden_dim: 128
# sweeper:
#   name: grid_tune
#   load_runs_from_queue: true
#   heartbeat_timeout: 30
#   num_runs: 3
#   parameters:
#     model:
#       hidden_dim: {values:[32, 64, 128, 256]}
# trainer:
#   scheduler: null
