name: DBC_ResidualActor
exp_mode: ???
overrides:
  model:
    encoder_mode: dbc
    residual_actor: True
sweeper:
  name: dbc_residualActor
  num_runs: 3
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}