name: KSME_ResidualActor
exp_mode: ???
overrides:
  model:
    encoder_mode: ksme
    residual_actor: True
sweeper:
  name: ksme_residualActor
  num_runs: 1
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}