name: NeuralEFKSME_Regularized
exp_mode: ???
overrides:
  model:
    encoder_mode: neural_ef_ksme
    encoder_type: pixel_l2
    decoder_type: pixel_l2
    trunk_regularization: true
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: neural_ef_ksme_regularized
  num_runs: 3
  parameters:
    model:
      trunk_regularization_coeff: {values: [1.0, 0.1, 0.01]}