name: NeuralEF
exp_mode: ???
overrides:
  model:
    encoder_mode: neural_ef
    encoder_type: pixel_l2
    decoder_type: pixel_l2
    trunk_regularization: true
  trainer:
    seed: 1
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: neural_ef_regularized
  num_runs: 3
  parameters:
    trainer:
      trainer_regularized_scale: {values: [1.0, 0.1, 0.01]}
