name: NeuralEF_RAP
exp_mode: ???
overrides:
  model:
    encoder_mode: neural_ef_rap
    rap_structural_distance: mico_angular
    rap_reward_dist: True
    rap_square_target: True
    encoder_type: pixel_l2
    decoder_type: pixel_l2
    epsilon: 1e-7
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: neural_ef_rap
  num_runs: 1
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}