name: NeuralEFKSME
exp_mode: ???
overrides:
  model:
    encoder_mode: neural_ef_ksme
    encoder_type: pixel_l2
    decoder_type: pixel_l2
    residual_actor: True
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: neural_ef_ksme_residualActor
  num_runs: 1
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}