name: NeuralEFMICO
exp_mode: ???
overrides:
  model:
    encoder_mode: neural_ef_mico
    encoder_type: pixel_l2
    decoder_type: pixel_l2
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: neural_ef_mico
  num_runs: 1
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}