name: NeuralEF
exp_mode: ???
overrides:
  model:
    encoder_mode: spectral
    encoder_type: pixel_l2
    decoder_type: pixel_l2
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: spectral
  num_runs: 3
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}