name: NeuralEF
exp_mode: ???
overrides:
  model:
    encoder_mode: spectral
    encoder_type: pixel_l2
    decoder_type: pixel_l2
    residual_actor: True
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
sweeper:
  name: spectral_residualActor
  num_runs: 10
  parameters:
    model:
      critic_lr: {values: [0.00001, 0.000001]}
      actor_lr: {values: [0.00001, 0.000001]}
      encoder_lr: {values: [0.00001, 0.000001]}