name: Test
exp_mode: ???
overrides:
  model:
    encoder_mode: dbc
  trainer:
    eval_freq: 100
    log_epoch_freq: 100
    init_steps: 10
    num_train_steps: 400
sweeper:
  name: test
  num_runs: 3
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}