name: Test
exp_mode: ???
overrides:
  model:
    encoder_mode: neural_ef
    encoder_type: pixel_l2
    decoder_type: pixel_l2
  trainer:
    env:
      encoder_type: pixel_l2
    eval_env:
      encoder_type: pixel_l2
    eval_freq: 100
    log_epoch_freq: 100
sweeper:
  name: test
  num_runs: 10
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}