model:
  module_path: src.studies.distance_invariance_study.models.ApproxSpectralNet
  optimizer:
    optimizer_kwargs:
      lr: 0.001
trainer:
  seed: 1
sweeper:
  name: approx_spectral_net
  num_runs: 10
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}
    model:
      optimizer:
        optimizer_kwargs:
          lr: {values: [0.01, 0.001, 0.0001]}