name: BaselineNet
exp_mode: ???
overrides:
  model:
    module_path: src.studies.distance_invariance_study.models.BaselineNet
sweeper:
  name: baseline_net
  num_runs: 10
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}
    model:
      optimizer:
        optimizer_kwargs:
          lr: {values: [0.001, 0.0001, 0.00001]}