name: graph
desc: |
 Evaluating on graph data
domain: graph
model_type: SingleMLPEigenFunctions
num_epochs: 5_000
overrides:
  model:
    input_size: 3
    optimizer:
      optimizer_kwargs:
        lr: 0.0001
  trainer:
    x_dim: 3