project: &project walker_new
sweeper:
  name: &sweep distraction_videos_test
  project: *project
  heartbeat_timeout: 3
  load_runs_from_queue: true
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}
trainer:
  project: *project
  save_checkpoint_freq: 500
  num_train_steps: &num_train_steps 3_000
  eval_freq: &eval_freq 300
  async_eval: true
  env:
    domain_name: &domain_name distracted_walker
    task_name: &task_name walk
    img_source: 'easy'
  storage:
    input:
      project: *project
    output:
      project: *project
model:
  encoder_mode: dbc
  decode_rewards_from_next_latent: True
evaluator:
  project: *project
  sweep: *sweep
  # run: kidmo5dl
  domain_name: *domain_name
  task_name: *task_name
logger:
  eval_freq: *eval_freq
  num_train_steps: *num_train_steps
