action_repeat: 1
actor_beta: 0.9
actor_log_std_max: 2
actor_log_std_min: -10
actor_lr: 0.001
actor_update_freq: 2
agent: bisim
alpha_beta: 0.9
alpha_lr: 0.001
batch_size: 256
bisim_coef: 0.5
boxed_env: false
critic_beta: 0.9
critic_lr: 0.001
critic_target_update_freq: 2
critic_tau: 0.005
decoder_lr: 0.001
decoder_type: pixel
decoder_update_freq: 1
decoder_weight_lambda: 0
discount: 0.99
distractor: None
domain_name: walker
encoder_feature_dim: 32
encoder_kernel_bandwidth: auto
encoder_lr: 0.0001
encoder_mode: spectral
encoder_normalize_loss: true
encoder_ortho_loss: 0.0001
encoder_ortho_loss_reg: 0.0001
encoder_output_dim: 32
encoder_stride: 1
encoder_tau: 0.005
encoder_type: pixel
episode_length: 500
eval_freq: 5
eval_img_sources:
- color
- mnist
- driving_stereo
eval_resource_files: null
frame_stack: 3
hidden_dim: 256
image_size: 84
img_source: null
init_steps: 1000
init_temperature: 0.01
k: 3
load_encoder: null
log_dir: logdir
logger: wandb
logger_img_downscale_factor: 3
logger_project: walker-exp-spectral
logger_video_log_freq: 5
num_eval_envs: 4
num_eval_episodes: 1
num_filters: 32
num_layers: 4
num_seeds: 1
num_train_steps: 70000
port: 2000
render: false
replay_buffer_capacity: 50000
resource_files: null
reward_decoder_num_rews: 1
save_buffer: false
save_model: false
save_tb: true
save_video: false
seed: 1
task_name: walk
total_frames: 500
transition_model_type: ''
work_dir: logdir
