project: gridworld
desc: |
  Testing the NeuralEF model on grid world dataset where observation=state=position on grid.
domain: 'gridworld'
optimizer: 
  name: Adam
  optimizer_kwargs:
    lr: 0.001
# scheduler: null
# scheduler:
#   type: linear
#   scheduler_kwargs: {
#     start_factor: 1.0,
#     end_factor: 0.1,
#     total_iters: 10_000,
#   }
scheduler:
  type: cosine
  scheduler_kwargs: {
    T_max: 2000
    }
trainer_module_path: src.neural_ef_study.modules_gridworld.NeuralEFTrainer
evaluator_module_path: src.neural_ef_study.modules_gridworld.NeuralEFEvaluator
model_module_path: src.neural_ef_study.modules_gridworld.NeuralEFModel
model_hidden_dim: 400