project: &project cartpole_test
sweeper:
  name: &sweep spectral_kinetics
  project: *project
  heartbeat_timeout: 30
  load_runs_from_queue: true
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}
trainer:
  project: *project
  eval_freq: &eval_freq 10_000
  num_train_steps: &num_train_steps 1_000_000
  env:
    domain_name: &domain_name cartpole
    task_name: &task_name swingup
    img_source: 'kinetics_videos'
  storage:
    input:
      project: *project
    output:
      project: *project
model:
  encoder_mode: spectral
evaluator:
  project: *project
  sweep: *sweep
  # run: kidmo5dl
  domain_name: *domain_name
  task_name: *task_name
logger:
  eval_freq: *eval_freq
  num_train_steps: *num_train_steps
