exp_mode: sweep
sweeper:
  name: dbc_kinetics
  parameters:
    trainer:
      seed: {values: [1, 2, 3]}
trainer:
  eval_freq: 200
  eval_env:
    episode_length: 20
  env:
    img_source: 'kinetics_videos'
model:
  encoder_mode: dbc
