project_name: bisim-reacher-tune
log_dir: /src/tune_results
n_trials: 100
hyperparams:
  decoder_lr:
    type: float 
    low: 0.001
    high: 0.2
    log: True
  hidden_dim: 
    type: categorical
    options: [128, 256, 512]
  task_name: 
    type: fixed
    value: circles
base_config:
  action_repeat: 1
  actor_beta: 0.9
  actor_log_std_max: 2
  actor_log_std_min: -10
  actor_lr: 0.001
  actor_update_freq: 2
  agent: bisim
  alpha_beta: 0.9
  alpha_lr: 0.001
  batch_size: 8
  bisim_coef: 0.5
  critic_beta: 0.9
  critic_lr: 0.001
  critic_target_update_freq: 2
  critic_tau: 0.005
  decoder_lr: 0.001
  decoder_type: pixel
  decoder_update_freq: 1
  decoder_weight_lambda: 0.0
  discount: 0.99
  domain_name: reacher
  encoder_feature_dim: 50
  encoder_kernel_bandwidth: auto
  encoder_lr: 0.001
  encoder_mode: spectral
  encoder_normalize_loss: true
  encoder_ortho_loss_reg: 0.0001
  encoder_stride: 1
  encoder_tau: 0.005
  encoder_type: pixel
  eval_freq: 1
  eval_resource_files: null
  frame_stack: 3
  hidden_dim: 256
  image_size: 84
  img_source: null
  init_steps: 10
  init_temperature: 0.01
  k: 3
  load_encoder: null
  logger: wandb
  num_eval_episodes: 1
  num_filters: 32
  num_layers: 4
  num_train_steps: 100
  port: 2000
  render: false
  replay_buffer_capacity: 10000
  resource_files: null
  reward_decoder_num_rews: 3
  save_buffer: false
  save_model: false
  save_tb: true
  save_video: true
  seed: 1
  task_name: circles
  total_frames: 1000
  transition_model_type: ''
  work_dir: .

